# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TopBrains' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TopBrains
#Firebase
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Storage'
  pod 'Firebase/Messaging'

#clean codes
  pod 'SwiftLint'

#for easier constraint
  pod 'SnapKit', '~> 5.0.0'

end
